### ISSUE TITLE
./install-dep.sh: line 100: PROJECT: unbound variable

### ISSUE THREAD

**Issue by huberylee** [hsnlab/escape#2]
When I try to install escape on Ubuntu 14.04, some errors have occurred:

```
root@58aef282f552:~/workspace/escape# ./install-dep.sh 
Detected platform is Ubuntu, version: 14.04!
=================================
==  Install core dependencies  ==
=================================
ESCAPEv2 version: 2.0.0
=== Setup project ===
./install-dep.sh: line 100: PROJECT: unbound variable
```
I did not find out the definition of ``PROJECT`` both  in ``install-dep.sh`` and system environemnt variable, so what should I do?

**Comment by czeni** [comment]
Unbound variable issue is fixed: https://github.com/hsnlab/escape/commit/d13ad17e7b01b5253f87ff41bd9f70130958d4a6
Nevertheless, I strongly suggest you to use the newer Ubuntu 16.04 LTS version as the supported default platform has been changed to the newer LTS for at least a year.

**Comment by huberylee** [comment]
ok, thank you very much!
